### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by farnaf** [fighterkabir/cse15l-lab-report#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
  - incorrect expected output
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
  - incorrect expected output
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
  - incorrect expected output
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
nice work 😃 
Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by fighterkabir** [comment]
How is the expected output incorrect? I used VS Code's markdown preview exactly to define the expected output.
Looks like common mark and VS Code give two different correct outputs, so this is a bit confusing as to which is the correct one. I used the VS Code one.

**Comment by fighterkabir** [comment]
Ok so update: A friend showed me his feedback for the lab report and in there the grader had commented what the correct expected output was. Since I was getting conflicting information from common mark and vs code, I decided to use that as my expected output (since it was the instructor) and just submitted a regrade request.

**Comment by farnaf** [comment]
Hi there! Sorry I missed the email notification from your earlier message. We consider a link valid when the URL that's used with a specific syntax/structure (e.g., `[]()`) turns into a *markdown link*. For example:

- `[hello](https://www.youtube.com/)` looks like this: [hello](https://www.youtube.com/)
  - we consider it valid because it turns into a link + we no longer see the URL
- `[hello] https://www.youtube.com/ `looks like this: [hello] https://www.youtube.com/
  - we don't consider it valid because GitHub highlights the URL as blue but doesn't turn anything into a markdown link

**Comment by farnaf** [comment]
The expected outputs look good. Updating your grade on Gradescope!

**Comment by fighterkabir** [comment]
Awesome, thank you!
